# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'
# Uncomment the next line to inhibit all warnings for your project
inhibit_all_warnings!


target 'PDFReader' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for PDFReader
  pod 'SnapKit', '~> 4.2.0'
end
